extends SceneTree
var failures: int = 0
var screenshots: String = ""
func _initialize() -> void: run.call_deferred()
func check(value: bool, caption: String) -> void:
	print(("PASS " if value else "FAIL ")+caption)
	if not value: failures += 1
func settle() -> void:
	for i: int in 6: await process_frame
func capture(name: String) -> void:
	if screenshots.is_empty(): return
	await create_timer(0.25).timeout
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png(screenshots.path_join(name+".png"))
func run() -> void:
	if OS.get_cmdline_user_args().size() > 0: screenshots = OS.get_cmdline_user_args()[0]
	root.size = Vector2i(1152,648)
	root.gui_embed_subwindows = true
	var app: Control = load("res://scenes/application_shell.tscn").instantiate()
	root.add_child(app)
	await settle()
	app.shared_settings.welcome.hide()
	app.choose_table(app.Mode.OFFLINE_PLAYTEST)
	app.table_chosen(false)
	check(app.entry.window.visible,"Standard opens familiar deck setup")
	app.entry.window.hide()
	app.choose_table(app.Mode.OFFLINE_PLAYTEST)
	app.table_chosen(true)
	await create_timer(0.65).timeout
	for i: int in 12: await process_frame
	var b: Node = app.table_scene.tabletop.custom_table
	var e: Node = b.editor
	check(e.empty.visible and not e.drawer.visible,"blank table shows centered onboarding")
	await capture("01-blank-table")
	e.open_drawer()
	check(e.drawer.visible,"open builder")
	e.toggle_drawer()
	check(not e.drawer.visible,"collapse builder")
	e.focus_search()
	check(e.drawer.search.has_focus(),"Ctrl+F target focuses component search")
	for alias: String in ["library","grave","board","shared"]:
		check(b.Doc.matches({"kind":{"library":"deck","grave":"discard","board":"board","shared":"shared_deck"}[alias],"name":""},alias),"search alias "+alias)
	e.drawer.search.release_focus()
	await capture("02-builder-open")
	e.begin_placement("zone")
	check(not e.pending_kind.is_empty() and b.document.components.is_empty(),"quick add enters ghost without spawning")
	var escape := InputEventKey.new()
	escape.keycode = KEY_ESCAPE
	escape.pressed = true
	e._input(escape)
	check(e.pending_kind.is_empty() and b.document.components.is_empty(),"Escape cancels ghost placement")
	e.begin_placement("zone")
	var item: Dictionary = e.place_at(Vector2(850,350))
	check(not item.is_empty() and item.position == [850.0,350.0],"click placement commits component at pointer")
	check(e.selected == item.id and b.views[item.id].resize_supported(),"component selected with resize handles")
	check(e.dirty(),"layout changes show unsaved indicator")
	e.begin_transform(item.id,Vector2(850,350),Vector2(1,1))
	e.transform_to(Vector2(1050,450))
	e.finish_gesture()
	check(b.row(item.id).size == [380.0,320.0],"corner drag resizes through validated operation")
	e.begin_transform(item.id,Vector2.ZERO)
	e.transform_to(Vector2(43,61))
	check(not e.guides.is_empty(),"move displays snap guides")
	e.finish_gesture()
	check(b.row(item.id).position != item.position,"move commits snapped position")
	e.select_component(item.id)
	await capture("03-selected-handles")
	b.update_component(item.id,{"locked":true})
	e.begin_transform(item.id,Vector2.ZERO)
	check(e.gesture.is_empty(),"locked component cannot move")
	b.update_component(item.id,{"locked":false,"owner":"player_1"})
	check(b.views[item.id].caption.text.begins_with("P1"),"ownership badge updates")
	var copy: Dictionary = e.duplicate_component(item.id,true)
	check(copy.id != item.id and copy.owner == "player_2" and b.orders.get(copy.id,[]).is_empty(),"duplicate other player has unique ID and no contents")
	b.update_component(copy.id,{"hidden":true})
	check(not b.views[copy.id].visible and not b.row(copy.id).is_empty(),"hidden object remains stored and listed")
	b.update_component(copy.id,{"hidden":false})
	check(b.views[copy.id].visible,"show component")
	e.lock_all(true)
	check(b.row(item.id).locked and b.row(copy.id).locked,"lock all")
	e.lock_all(false)
	check(not b.row(item.id).locked and not b.row(copy.id).locked,"unlock all")
	for entry: Dictionary in b.document.components.duplicate(true): b.remove_component(entry.id)
	e.recipe(true)
	check(b.document.components.size() == 5,"shared recipe creates five editable components")
	var shared: String = b.primary_for("player_1")
	check(shared == b.primary_for("player_2") and b.views[shared].caption.text.contains("SHARED DRAW"),"shared ownership and primary draw badge")
	b.update_component(shared,{"hidden":true})
	check(b.primary_for("player_1") == shared,"hiding a pile does not change its draw assignment")
	b.update_component(shared,{"hidden":false})
	var image := Image.create(300,200,false,Image.FORMAT_RGB8)
	image.fill(Color("294759"))
	var stored: Dictionary = b.assets.store(image.save_png_to_buffer())
	var record: Dictionary = {"name":"Fixture","image_path":b.assets.path(stored.hash),"metadata":{"card_id":"ux_fixture"},"thumbnail":ImageTexture.create_from_image(image)}
	b.put_card(b.manager.spawn_definition(record,false).card,shared)
	check(not b.remove_component(shared),"occupied removal protected")
	var duplicate: Dictionary = e.duplicate_component(shared)
	check(b.orders.get(duplicate.id,[]).is_empty(),"duplicate pile never copies cards")
	check(e.drawer.relocate(shared,duplicate.id) and b.orders[duplicate.id].size() == 1,"occupied component moves cards safely to another pile")
	b.set_primary(duplicate.id)
	e.drawer.hide()
	b.manager.view.zoom = 0.5
	b.manager.view.pan = Vector2(60,100)
	b.manager.view.apply_view()
	await capture("04-shared-deck-table")
	var board: Dictionary = b.add_component("board")
	b.update_component(board.id,{"asset":stored.hash,"position":[300,250],"size":[1800,1050]})
	e.select_component(board.id)
	e.drawer.hide()
	await capture("05-board-image-table")
	b.document.name = "Shared Party Table"
	e.templates.request_save(b.document)
	check(not e.dirty(),"save clears unsaved indicator")
	check(b.storage.list_templates().size() == 1,"saved table appears in My Tables")
	var original: Dictionary = b.document.duplicate(true)
	var duplicated: Dictionary = b.storage.duplicate_template(original)
	check(not duplicated.has("error") and duplicated.table.id != original.id,"duplicate template gets new ID")
	duplicated.table.name = "Party Copy Renamed"
	check(not b.storage.save(duplicated.table).has("error"),"rename template copy")
	check(not b.storage.export_file(original,"user://Shared-Party-Table.cltemplate",false).has("error"),"export original template")
	check(b.storage.delete_template(duplicated.table.id).is_empty(),"delete copy")
	check(not b.storage.delete_template("standard").is_empty(),"built-in Standard cannot be deleted")
	e.templates.apply_loaded(original)
	check(b.document.components.size() == original.components.size() and not e.dirty(),"reload original preserves table structure")
	check(b.primary_for("player_1") == duplicate.id and b.primary_for("player_2") == duplicate.id,"Primary Draw assignment survives template reload")
	e.templates.open_manager()
	await capture("06-my-tables")
	e.templates.hide()
	b.manager.layout.set_edit_mode(false)
	await settle()
	check(not e.drawer.visible and e.gesture.is_empty() and e.guides.is_empty(),"Play Mode hides edit UI and guides")
	check(b.views[board.id].mouse_filter == Control.MOUSE_FILTER_IGNORE,"board ignores normal play clicks")
	await capture("07-play-mode")
	b.manager.layout.set_edit_mode(true)
	e.select_component(board.id)
	check(e.drawer.visible,"Build Mode restores editing selection")
	for screen: Vector2i in [Vector2i(1920,1080),Vector2i(960,540)]:
		root.size = screen
		root.content_scale_size = screen
		await create_timer(0.3).timeout
		await settle()
		e.fit()
		await settle()
		print("SIZE ",screen," viewport ",root.get_visible_rect().size," drawer ",e.drawer.size," at ",e.drawer.position)
		check(e.drawer.position.y+e.drawer.size.y <= root.get_visible_rect().size.y and e.drawer.size.x < root.get_visible_rect().size.x/2,"drawer fits "+str(screen))
		await capture("builder-%dx%d" % [screen.x,screen.y])
	root.size = Vector2i(1152,648)
	root.content_scale_size = Vector2i(1152,648)
	await create_timer(0.3).timeout
	for entry: Dictionary in b.document.components.duplicate(true): b.remove_component(entry.id,true)
	e.recipe(false)
	check(b.document.components.size() == 5,"simple recipe creates editable P1/P2 decks, hands and shared area")
	check(b.primary_for("player_1") != b.primary_for("player_2"),"simple recipe gives each player independent Primary Draw")
	var simple_board: Dictionary = b.add_component("board")
	b.update_component(simple_board.id,{"asset":stored.hash,"position":[200,240],"size":[1900,1000]})
	e.drawer.hide()
	await capture("08-simple-table")
	e.templates.request_save(b.document)
	check(e.templates.overwrite.visible,"saving existing table offers Update or Save Copy")
	e.templates.overwrite.hide()
	e.templates.finish_save(true)
	check(b.document.id != original.id,"Save Copy keeps original template ID intact")
	check(not b.manager.shortcuts.bindings.caption("table_builder").is_empty(),"builder shortcut can be assigned without replacing defaults")
	e.open_drawer()
	for i: int in 36: b.add_component("zone")
	await settle()
	var child_id: int = e.drawer.content.get_child(0).get_instance_id()
	await settle()
	check(e.drawer.content.get_child(0).get_instance_id() == child_id,"dozens of components do not rebuild the drawer each frame")
	app.dispose_table()
	app.queue_free()
	await settle()
	print("BUILDER UX FAILURES: ",failures)
	quit(0 if failures == 0 else 1)
