extends SceneTree
var failures: int = 0
func check(value: bool, caption: String) -> void:
	print(("PASS " if value else "FAIL ")+caption)
	if not value: failures += 1
func _initialize() -> void: run.call_deferred()
func run() -> void:
	var app: Control = load("res://scenes/application_shell.tscn").instantiate()
	root.add_child(app)
	for i: int in 8: await process_frame
	app.shared_settings.welcome.hide()
	app.choose_table(app.Mode.OFFLINE_PLAYTEST)
	check(app.table_selection.visible,"table choice opens")
	app.table_chosen(false)
	check(app.entry.window.visible,"Standard opens existing offline setup")
	app.entry.window.hide()
	app.choose_table(app.Mode.OFFLINE_PLAYTEST)
	app.table_chosen(true)
	for i: int in 45: await process_frame
	var b: Node = app.table_scene.tabletop.custom_table
	b.panel.hide()
	check(b.enabled and b.document.components.is_empty() and b.manager.zones.is_empty(),"Build Your Own starts blank")
	var main: Dictionary = b.add_component("deck","player_1")
	var side: Dictionary = b.add_component("deck","player_1")
	var extra: Dictionary = b.add_component("deck","player_1")
	var shared: Dictionary = b.add_component("shared_deck")
	var discard: Dictionary = b.add_component("discard")
	check(main.id != side.id and side.id != extra.id,"multiple independent piles")
	check(shared.owner == "table","shared pile table ownership")
	b.add_component("hand","player_1")
	b.add_component("hand","player_2")
	var zone: Dictionary = b.add_component("zone")
	check(b.update_component(zone.id,{"name":"Bench","hidden":true}),"rename and hide zone")
	check(not b.views[zone.id].visible,"hidden component not shown")
	b.update_component(zone.id,{"hidden":false})
	check(b.views[zone.id].visible,"show component")
	check(b.remove_component(zone.id),"remove empty component")
	check(b.Doc.matches(main,"library"),"component alias search")
	var image := Image.create(750,1050,false,Image.FORMAT_RGB8)
	image.fill(Color.DARK_CYAN)
	var stored: Dictionary = b.assets.store(image.save_png_to_buffer())
	check(stored.has("hash"),"bounded board image storage")
	var board: Dictionary = b.add_component("board")
	b.update_component(board.id,{"asset":stored.hash,"locked":true})
	b.manager.layout.set_edit_mode(false)
	check(b.views[board.id].mouse_filter == Control.MOUSE_FILTER_IGNORE,"locked board ignores normal selection")
	b.manager.layout.set_edit_mode(true)
	check(b.views[board.id].mouse_filter == Control.MOUSE_FILTER_STOP,"board editable in Layout mode")
	var record: Dictionary = {"name":"Practice","image_path":b.assets.path(stored.hash),"metadata":{"card_id":"practice"},"thumbnail":ImageTexture.create_from_image(image)}
	for i: int in 4:
		var card: Control = b.manager.spawn_definition(record,false).card
		b.put_card(card,shared.id)
	check(b.orders[shared.id].size() == 4,"shared pile contains copies")
	check(b.draw(shared.id,"player_1") and b.draw(shared.id,"player_2"),"shared draw to both players")
	check(b.manager.match_controller.model.players.local.hand.size() == 1 and b.manager.match_controller.model.players.opponent.hand.size() == 1,"separate hands")
	var card: Control = b.manager.match_controller.card_by_id(b.orders[shared.id][0])
	check(b.put_card(card,discard.id),"shared discard accepts card")
	check(not b.remove_component(discard.id),"occupied removal requires confirmation")
	var card_store = preload("res://scripts/card_storage.gd").new("user://fixture_cards")
	var fixture: Dictionary = card_store.save_card(image.save_png_to_buffer(),"Fixture",image.get_size())
	b.manager.match_controller.loader = preload("res://scripts/library_loader.gd").new("user://fixture_cards")
	var deck_data: Dictionary = preload("res://scripts/deck_storage.gd").new_deck()
	deck_data.cards = [{"card_id":fixture.metadata.card_id,"quantity":2}]
	check(b.load_deck(main.id,deck_data).is_empty() and b.load_deck(side.id,deck_data).is_empty() and b.load_deck(extra.id,deck_data).is_empty(),"load three independent decks")
	b.draw(side.id,"player_1")
	check(b.orders[main.id].size() == 2 and b.orders[side.id].size() == 1 and b.orders[extra.id].size() == 2,"drawing one pile leaves other piles unchanged")
	b.manager.extras.create_counter(Vector2(500,500),7,"Round")
	b.manager.create_token("Marker","local","local","","2","3")
	b.capture_template_defaults()
	check(b.document.defaults.size() == 2 and b.Doc.validate(b.document).is_empty(),"counter and token defaults are data only")
	var saved: Dictionary = b.storage.save(b.document)
	check(not saved.has("error"),"save template")
	check(not b.storage.save(b.document).has("error"),"updating an existing template saves safely")
	var read: Dictionary = b.storage.preview(saved.path)
	check(read.table == JSON.parse_string(JSON.stringify(b.document)),"load template")
	var export_path: String = "user://roundtrip.cltemplate"
	check(not b.storage.export_file(b.document,export_path,false).has("error"),"export template without images")
	check(b.storage.preview(export_path).images.is_empty(),"template excludes card collection and images by default")
	var other = preload("res://scripts/custom_table/template_storage.gd").new()
	other.directory = "user://clean_templates"
	other.assets.directory = "user://clean_images"
	var clean: Dictionary = other.import_file(export_path)
	check(not clean.has("error") and clean.missing.size() == 1,"clean import with missing optional image")
	var bad: Dictionary = b.document.duplicate(true)
	bad.components[0].position = [INF,0]
	check(not b.Doc.validate(bad).is_empty(),"reject extreme coordinates")
	bad = b.document.duplicate(true)
	bad.components[0].script = "res://anything.gd"
	check(not b.Doc.validate(bad).is_empty(),"reject executable/unrecognized fields")
	check(not b.storage.export_file(b.document,"user://with-board.cltemplate",true).has("error"),"opt-in board export")
	var included: Dictionary = other.import_file("user://with-board.cltemplate")
	check(not included.has("error") and FileAccess.file_exists(other.assets.path(stored.hash)),"included board imports and verifies hash")
	var malicious: Dictionary = b.document.duplicate(true)
	malicious.components[0].asset = "../../outside.png"
	check(not b.Doc.validate(malicious).is_empty(),"reject external image paths")
	var match_save: Dictionary = b.manager.persistence.capture_match()
	var validation: String = preload("res://scripts/match_snapshot.gd").validate(match_save)
	check(validation.is_empty(),"custom match validates: "+validation)
	check(not b.manager.persistence.restore_match(match_save).has("error"),"match save/load restores custom table")
	check(b.orders.get(shared.id,[]).size() == 1,"match preserves shared pile order")
	match_save.local_tabletop.erase("custom_table")
	check(preload("res://scripts/match_snapshot.gd").validate(match_save).is_empty(),"older save without extension still validates")
	var template_copy: Dictionary = b.document.duplicate(true)
	b.apply_template(template_copy)
	var before_defaults: int = b.manager.cards.size() + b.manager.extras.counters.size()
	b.apply_template(template_copy)
	check(b.manager.cards.size() + b.manager.extras.counters.size() == before_defaults,"reloading unchanged template does not duplicate defaults")
	app.dispose_table()
	app.queue_free()
	for i: int in 4: await process_frame
	print("CUSTOM TABLE FAILURES: ",failures)
	quit(0 if failures == 0 else 1)
