extends "res://scripts/tests/milestone_74_test.gd"
func make_zip(path: String, color: Color = Color.RED) -> void:
	var zip := ZIPPacker.new()
	zip.open(path)
	for i: int in 2:
		var art := Image.create(750,1050,false,Image.FORMAT_RGBA8)
		art.fill(Color.BLUE if i == 0 else color)
		zip.start_file("nested/Example - "+("Front" if i == 0 else "Back")+".png")
		zip.write_file(art.save_png_to_buffer())
		zip.close_file()
	zip.close()
func capture_ui(base: String, label: String) -> void:
	if not OS.get_cmdline_user_args().has("capture"): return
	for _i: int in 3: await process_frame
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png(base.path_join(label+".png"))
func run() -> void:
	var base: String = OS.get_cmdline_user_args()[0]
	root.size = Vector2i(1152,760)
	root.gui_embed_subwindows = true
	var importer: Window = preload("res://ui/card_importer.tscn").instantiate()
	importer.storage = preload("res://scripts/card_storage.gd").new(base.path_join("manual"))
	root.add_child(importer)
	var image := Image.create(800,1100,false,Image.FORMAT_RGBA8)
	image.fill(Color.BLUE)
	image.save_png(base.path_join("Front.png"))
	importer.select_file(base.path_join("Front.png"))
	await importer.confirm_crop()
	importer.open_importer()
	await capture_ui(base,"importer")
	importer.hide()
	var id: String = importer.last_definition.card_id
	check(importer.add_face_button.disabled == false,"Importer offers Add Another Face after first save")
	image.fill(Color.RED)
	image.save_png(base.path_join("Back.png"))
	importer.adding_face = true
	importer.select_file(base.path_join("Back.png"))
	await importer.confirm_crop()
	check(importer.last_definition.card_id == id and importer.last_definition.faces.size()==2,"Importer appends face to same definition ID")
	check(DirAccess.get_files_at(base.path_join("manual/definitions")).size()==1,"Manual two-face import creates only one definition")
	for face: Dictionary in importer.last_definition.faces:
		var loaded := Image.new()
		loaded.load(face.image_path)
		check(loaded.get_size()==Vector2i(750,1050),"Each imported face uses existing normalization")
	var loader = preload("res://scripts/library_loader.gd").new(base.path_join("manual"))
	var builder: Control = preload("res://scripts/deck_builder.gd").new()
	builder.loader = loader
	root.add_child(builder)
	builder.records = loader.load_records()
	builder.refresh_catalog()
	builder.catalog.select(0)
	builder.add_selected()
	check(builder.deck.cards.size()==1 and builder.deck.cards[0].quantity==1,"Deck Builder counts two-face card as one slot")
	builder.show_preview(id)
	builder.show_face(1)
	check(builder.preview_face==1 and builder.preview.texture!=null,"Deck Builder alternate preview")
	builder.show()
	await capture_ui(base,"deck-builder")
	builder.hide()
	var extra: Dictionary = importer.storage.save_card(image.save_png_to_buffer(),"Another piece",image.get_size())
	var library: Control = preload("res://scripts/card_library.gd").new()
	library.loader = loader
	root.add_child(library)
	library.refresh()
	library.select_record(base.path_join("manual/definitions").path_join(id+".json"))
	library.show()
	library.size = Vector2(1152,760)
	await capture_ui(base,"library")
	library.face_tools.open_combine()
	library.face_tools.commit_combine()
	check(loader.load_records().size()==3,"Combine UI creates one new definition and retains originals")
	check(library.face_tools.current.metadata.faces.size()==3,"Combine UI supports more than two faces")
	library.queue_free()
	var path: String = base.path_join("Paired.zip")
	make_zip(path)
	var service = preload("res://scripts/archive_import_service.gd").new(base.path_join("archive"),base.path_join("decks"))
	var plan: Dictionary = service.preview(path)
	check(not plan.has("error") and plan.rows.size()==2,"Archive defaults to separate definitions")
	var pairs = preload("res://scripts/archive_face_pairs.gd")
	check(pairs.detect(plan.rows).size()==1,"Exact nested Front/Back names detected")
	pairs.configure(plan,service.cards.directory,true)
	check(plan.rows.size()==1 and plan.rows[0].face_rows.size()==2,"Explicit Combine makes one planned definition")
	pairs.configure(plan,service.cards.directory,false)
	check(plan.rows.size()==2,"Keep Separate restores original plan")
	pairs.configure(plan,service.cards.directory,true)
	var result: Dictionary = service.commit(plan)
	check(not result.has("error") and result.deck.cards.size()==1 and result.copies==1,"Combined ZIP commits one deck slot")
	check(DirAccess.get_files_at(base.path_join("archive/definitions")).size()==1,"No extra front/back definitions created")
	plan = service.preview(path)
	pairs.configure(plan,service.cards.directory,true)
	check(plan.stats.existing==1 and plan.stats.new==0,"Repeat paired archive reuses definition")
	check(plan.candidates.size()==1 and plan.candidates[0].diff.unchanged.size()==1,"Repeat paired archive comparison unchanged")
	result = service.commit(plan,0,false)
	check(not result.has("error") and result.created_definitions==0,"Repeat update creates no duplicate assets/definitions")
	make_zip(path,Color.GREEN)
	plan = service.preview(path)
	pairs.configure(plan,service.cards.directory,true)
	check(plan.candidates[0].diff.artwork.size()==1,"Changed back artwork is detected even when front unchanged")
	result = service.commit(plan,0,false)
	check(not result.has("error") and result.created_definitions==1,"Changed back creates safe new definition")
	check(DirAccess.get_files_at(base.path_join("archive/definitions")).size()==2,"Old multi-face definition retained")
	check(DirAccess.get_files_at(base.path_join("archive")).size()==3,"Unchanged front reused; old back retained")
	var ambiguous: Array = [{"name":"Piece_front","files":["one/Piece_front.png"],"quantity":1},{"name":"Piece_back","files":["two/Piece_back.png"],"quantity":1}]
	check(pairs.detect(ambiguous).is_empty(),"Different-folder names are not automatically paired")
	builder.queue_free(); importer.queue_free()
	await process_frame
	print("CARDLINK 7.7 IMPORT: %d checks, %d failures" % [checks,failures])
	quit(1 if failures else 0)
