extends "res://scripts/tests/milestone_6b_test.gd"
func run() -> void:
	var base: String = OS.get_cmdline_user_args()[0]
	root.gui_embed_subwindows = true
	var a: Control = await create_client(base.path_join("a"),"HOST_SECRET",Color.BLUE)
	var b: Control = await create_client(base.path_join("b"),"GUEST_SECRET",Color.RED)
	var ua: Node = a.get_node("Network")
	var ub: Node = b.get_node("Network")
	var ra: Node = ua.gameplay
	var rb: Node = ub.gameplay
	var ha: Node = ra.hidden
	var hb: Node = rb.hidden
	ha.settings_path = base.path_join("host.cfg")
	hb.settings_path = base.path_join("guest.cfg")
	ha.auto_approve = false
	hb.auto_approve = false
	var ca: Node = a.tabletop.match_controller
	var cb: Node = b.tabletop.match_controller
	var port: int = randi_range(33000,43000)
	ua.network.host_game(port,"Host","127.0.0.1")
	ub.network.join_game("127.0.0.1",port,"Guest")
	check(await wait_for(func() -> bool: return ua.network.session.state == "connected" and ub.network.session.state == "connected"),"Connected")
	ra.start()
	rb.start()
	await wait_for(func() -> bool: return ra.card_sync.checked and rb.card_sync.checked)
	ra.card_sync.decide("sync")
	await wait_for(func() -> bool: return ra.card_sync.status.begins_with("CARD SYNC COMPLETE") and rb.card_sync.status.begins_with("CARD SYNC COMPLETE"),15)
	ra.card_sync.decide("start")
	rb.card_sync.decide("start")
	check(await wait_for(func() -> bool: return ra.enabled and rb.enabled),"Shared match starts")
	var before_toggle: int = wire.size()
	a.tabletop.shortcuts.hands_button.pressed.emit()
	a.tabletop.shortcuts.hands_button.pressed.emit()
	check(wire.size() == before_toggle,"Connected hand toggle emits no network action")
	ca.library_actions.draw_n("local",3)
	cb.library_actions.draw_n("local",3)
	await settle()
	check(ra.state.hands[ra.remote_id].is_empty(),"Normal hand has no remote identities")
	var first: Control = cb.card_by_id(cb.model.players.local.hand[0])
	cb.toggle_hand_reveal(first)
	await settle()
	check(ra.state.hands[ra.remote_id].size() == 1,"One reveal exposes only one hand card")
	cb.toggle_hand_reveal(first)
	await settle()
	check(ra.state.hands[ra.remote_id].is_empty(),"Hide removes normal presentation identity")
	hb.reveal_hand(true)
	await settle()
	check(ra.state.hands[ra.remote_id].size() == 3,"Reveal Hand exposes current three cards")
	cb.draw_card()
	await settle()
	check(ra.state.hands[ra.remote_id].size() == 3 and ca.hidden_count("opponent","hand") == 4,"Future draw stays hidden")
	hb.reveal_hand(false)
	await settle()
	check(ra.state.hands[ra.remote_id].is_empty(),"Hide Hand removes temporary faces")
	for zone: String in ["hand","library"]:
		var before: int = wire.size()
		ha.request(zone)
		check(await wait_for(func() -> bool: return hb.incoming != null and hb.ui.prompt.visible),"Remote Allow/Deny prompt: " + zone)
		hb.respond(false)
		check(await wait_for(func() -> bool: return ha.outgoing == null),"Denial closes request: " + zone)
		check(not wire.slice(before).any(func(f: Dictionary) -> bool: return f.type == "hidden_zone" and f.kind in ["snapshot","transfer"]),"Denied " + zone + " transmits no identities")
	ha.request("hand")
	await wait_for(func() -> bool: return hb.incoming != null)
	hb.respond(true)
	check(await wait_for(func() -> bool: return ca.remote_inspection and ca.contents_list.item_count == 4),"Approved hand opens existing visual gallery")
	check(ca.contents_list.get_item_icon(0) != null,"Gallery resolves transferred image")
	check(ra.state.hands[ra.remote_id].is_empty(),"Inspection never changes ordinary hand backs")
	var future: String = cb.pile.order[0]
	cb.draw_card()
	await settle()
	check(not ha.outgoing.rows.any(func(row: Dictionary) -> bool: return row.id == future),"New draw does not enter an already authorized hand inspection")
	check(not JSON.stringify(ra.serializer.capture()).contains(first.state.match_instance_id),"Temporary identities excluded from public resync")
	var held: RefCounted = ha.outgoing
	ca.close_inspection()
	await settle()
	check(ha.outgoing == null and hb.incoming == null and held.rows.is_empty() and ca.inspection_preview.texture == null and ca.contents_list.item_count == 0,"Closing revokes permission and clears identities/previews")
	ha.request("library")
	await wait_for(func() -> bool: return hb.incoming != null)
	var order_before: Array = cb.pile.order.duplicate()
	hb.respond(true)
	await wait_for(func() -> bool: return ca.remote_inspection)
	check(ha.outgoing.rows.map(func(row: Dictionary) -> String: return row.id) == order_before,"Approved library shows actual temporary order")
	ca.contents_list.select(0)
	var moved: String = str(ca.contents_list.get_item_metadata(0))
	ha.move_selected("library",3)
	check(await wait_for(func() -> bool: return cb.pile.order.find(moved) == 2),"Owner executes Nth-from-top")
	await settle()
	ca.contents_list.select(2)
	ha.move_selected("library",2,true)
	check(await wait_for(func() -> bool: return cb.pile.order.find(moved) == cb.pile.order.size()-2),"Owner executes Nth-from-bottom")
	var marker: int = wire.size()
	ca.close_inspection()
	await settle()
	check(hb.incoming == null and cb.model.history.any(func(e: Dictionary) -> bool: return e.text.contains("shuffled")),"Closing library search shuffles on owner")
	check(not wire.slice(marker).any(func(f: Dictionary) -> bool: return f.type == "hidden_zone" and f.kind == "snapshot" and (not str(f.request_id).begins_with("library_memory_") or not f.data.cards.is_empty())),"Shuffle sends only empty knowledge reset, never shuffled identities/order")
	hb.set_auto_approve(true)
	var prefs := ConfigFile.new()
	prefs.load(hb.settings_path)
	check(prefs.get_value("privacy","auto_approve",false) == true,"Auto-approval preference persists locally")
	ha.request("hand")
	check(await wait_for(func() -> bool: return ca.remote_inspection),"Trusted auto-approval works")
	ca.contents_list.select(0)
	var taken: String = str(ca.contents_list.get_item_metadata(0))
	ha.move_selected("take")
	check(await wait_for(func() -> bool: return ca.card_by_id(taken) != null and cb.card_by_id(taken) == null),"Taking card transfers one private instance")
	var taken_card: Control = ca.card_by_id(taken)
	check(taken_card != null and taken_card.state.owner_player_id == "opponent" and taken_card.state.controller_player_id == "opponent" and taken_card.state.zone_player_id == "local" and taken_card.state.current_zone == "hand","Private transfer preserves owner/controller and updates holder")
	await settle()
	check(rb.state.hands[rb.remote_id].is_empty() and cb.hidden_count("opponent","hand") == 4,"New private holder exposes only count/back")
	ca.close_inspection()
	ca.move_card(taken_card,"battlefield")
	check(await wait_for(func() -> bool: return rb.state.cards.has(taken)),"New holder can play the other owner's card publicly")
	ha.request("hand")
	await wait_for(func() -> bool: return ca.remote_inspection)
	ca.contents_list.select(0)
	var public_id: String = str(ca.contents_list.get_item_metadata(0))
	ha.move_selected("battlefield")
	check(await wait_for(func() -> bool: return ra.state.cards.has(public_id)),"Inspected card may move directly to public battlefield")
	ca.close_inspection()
	await settle()
	for zone: String in ["graveyard","exile"]:
		ha.request("library")
		await wait_for(func() -> bool: return ca.remote_inspection)
		ca.contents_list.select(0)
		var inspect_id: String = str(ca.contents_list.get_item_metadata(0))
		ha.move_selected(zone)
		check(await wait_for(func() -> bool: return ra.state.cards.has(inspect_id) and ra.state.cards[inspect_id].zone == zone),"Approved move to " + zone + " synchronizes publicly")
		ca.close_inspection()
		await settle()
	hb.auto_approve = false
	ha.request("hand")
	await wait_for(func() -> bool: return hb.incoming != null)
	hb.incoming.expires = hb.now()-1
	hb._process(0)
	check(await wait_for(func() -> bool: return ha.outgoing == null and hb.incoming == null),"Request timeout revokes pending access")
	hb.auto_approve = true
	ha.request("hand")
	await wait_for(func() -> bool: return ca.remote_inspection)
	var denied_id: String = cb.pile.order[0]
	var denied_zone: String = cb.card_by_id(denied_id).state.current_zone
	hb.apply_move({"id":denied_id,"destination":"exile","n":1,"bottom":false})
	check(cb.card_by_id(denied_id).state.current_zone == denied_zone,"Move outside authorized zone is rejected")
	ca.close_inspection()
	await settle()
	ha.request("hand")
	await wait_for(func() -> bool: return ca.remote_inspection)
	var owner_count: int = cb.model.players.local.hand.size()
	ua.network.disconnect_session()
	await settle()
	check(ha.outgoing == null and hb.incoming == null and not ca.contents.visible and ca.contents_list.item_count == 0,"Disconnect revokes access and clears temporary gallery")
	check(cb.model.players.local.hand.size() == owner_count,"Disconnect preserves owner state")
	check(not JSON.stringify(ra.state.history).contains("GUEST_SECRET"),"History contains no hidden card names")
	a.queue_free()
	b.queue_free()
	await process_frame
	print("MILESTONE 6C: %d checks, %d failures" % [checks,failures])
	quit(0 if failures == 0 else 1)
