extends "res://scripts/tests/milestone_74_test.gd"
func run() -> void:
	var base: String = OS.get_cmdline_user_args()[0]
	root.size = Vector2i(1152,760)
	root.gui_embed_subwindows = true
	var app: Control = new_app(base)
	await process_frame
	var title: Control = app.title_screen
	var motion: Node = title.animation
	check(title.visible and app.table_scene == null,"Title opens without starting a match")
	check(app.title_screen.composition.get_node("BuildVersion").text == preload("res://scripts/frontend/app_info.gd").LABEL,"Title uses current central version")
	motion.set_focused(true)
	motion._process(0.1)
	check(motion.ring.rotation > 0,"Independent tech arcs rotate")
	check(title.title_art.self_modulate.r != 1.0 and title.title_art.rotation == 0,"Logo pulses without rotating lettering")
	check(title.background.scale.x > 1 and title.background.position != Vector2.ZERO,"Subtle background drift covers edges")
	for button: Button in title.buttons:
		button.grab_focus()
		button.update_feedback()
		await create_timer(0.17).timeout
		check(button.hover_amount > 0.9,"Focus/hover response: "+button.name)
		check(button.get_theme_stylebox("focus") is StyleBoxEmpty,"Artwork uses its own clear focus border: "+button.name)
	motion.set_focused(false)
	check(not motion.is_processing(),"Continuous title animation pauses when unfocused")
	motion.set_focused(true)
	check(motion.is_processing(),"Title animation resumes on focus")
	app.table_preferences.put("reduce_motion",true)
	check(not motion.is_processing() and motion.ring.rotation == 0,"Reduce Motion stops ring and processing")
	check(title.background.scale == Vector2.ONE and title.title_art.self_modulate == Color.WHITE,"Reduce Motion restores static background/logo")
	title.buttons[0].grab_focus()
	title.buttons[0].update_feedback()
	check(title.buttons[0].has_focus() and title.buttons[0].hover_amount == 0,"Reduced-motion buttons retain focus without movement")
	app.shared_settings.open()
	check(title.settings.visible,"Settings still usable with Reduce Motion")
	await screenshot(base,"settings")
	title.settings.hide()
	app.table_preferences.put("reduce_motion",false)
	await screenshot(base,"title")
	title.offline_requested.emit()
	check(app.entry.window.visible and app.table_scene == null,"Offline panel opens setup rather than starting immediately")
	check(app.entry.player_names.size() == 2 and app.entry.player_lives.size() == 2 and app.entry.deck_pickers.size() == 2,"Setup provides two names/decks/life values")
	await screenshot(base,"setup")
	app.entry.player_names.assign(["Ada","Grace"])
	app.entry.player_lives.assign([20,30])
	app.entry.setup_ready = true
	app.entry.start(app.Mode.OFFLINE_PLAYTEST)
	check(app.entering,"Title-to-table transition guards duplicate entry")
	check(await wait_for(func() -> bool: return app.table_scene != null and not app.entering),"Title-to-table transition completes")
	check(not motion.is_processing(),"Hidden title does no continuous animation work")
	var table: Node = app.table_scene.tabletop
	var c: Node = table.match_controller
	app.presenter.refresh()
	check(c.model.players.local.display_name == "Ada" and c.model.players.opponent.display_name == "Grace","Configured offline names survive presenter refresh")
	check(c.model.players.local.life == 20 and c.model.players.opponent.life == 30,"Independent starting life applied")
	check(is_equal_approx(c.hand.get_theme_stylebox("panel").bg_color.a,0.5),"Local hand defaults to 50 percent background")
	check(is_equal_approx(c.opponent_hand.get_theme_stylebox("panel").bg_color.a,0.5),"Far hand defaults to 50 percent background")
	var token: Control = table.create_token("Opacity fixture","local","local","","2","2").card
	token.state.is_token = false
	var art := Image.create(750,1050,false,Image.FORMAT_RGBA8)
	art.fill(Color.CORNFLOWER_BLUE)
	token.card_image.texture = ImageTexture.create_from_image(art)
	c.move_card(token,"hand",true,"local")
	c.refresh()
	var item: Control = c.hand.row.get_child(0)
	check(item.modulate.a == 1 and item.self_modulate.a == 1 and c.hand.modulate.a == 1,"Hand cards retain full opacity independent of background")
	check(item.texture != null,"Hand face image remains present")
	c.opponent_hand.present(1,table.backs.texture())
	var hidden: Control = c.opponent_hand.cards_row.get_child(0)
	check(hidden.texture == table.backs.texture() and hidden.modulate.a == 1 and c.opponent_hand.modulate.a == 1,"Hidden backs remain opaque without identity")
	check(c.hand.label.modulate.a == 1,"Hand text retains full opacity")
	table.select_card(token)
	check(table.selected_card == token,"Selection remains usable in transparent hand")
	c.hand_window.open_hand()
	check(c.hand.get_parent() == c.hand_window.rows and c.hand.modulate.a == 1,"Detached hand reuses opaque card presentation")
	check(c.hand_window.window.has_meta("cardlink_skin"),"Detached window has matching dark-blue styling")
	app.table_preferences.put("hand_opacity",0.7)
	check(is_equal_approx(c.hand.get_theme_stylebox("panel").bg_color.a,0.7),"Opacity updates detached hand live")
	var prefs = preload("res://scripts/usability/table_preferences.gd").new(app.table_preferences.path)
	check(is_equal_approx(float(prefs.value("hand_opacity",0)),0.7),"Opacity persists")
	app.table_preferences.put("hand_opacity",0.0)
	check(is_equal_approx(c.hand.get_theme_stylebox("panel").bg_color.a,0.2),"Opacity safely clamps to 20 percent")
	app.table_preferences.put("hand_opacity",0.5)
	c.end_turn()
	check(table.perspective.feedback.label.text.contains("PLAYER 2 TURN") and table.perspective.feedback.label.visible,"Player 2 turn cue appears")
	check(table.perspective.feedback.label.mouse_filter == Control.MOUSE_FILTER_IGNORE,"Turn cue never blocks card input")
	check(c.hearts.hearts.opponent.get_theme_color("font_color") == Color("8beaff"),"Active player life accent follows turn")
	table.perspective.toggle()
	check(table.perspective.feedback.label.text.contains("PLAYER 2 TURN") and table.perspective.feedback.label.text.contains("Viewing Player 1"),"Manual seat cue distinguishes viewed seat from active turn")
	c.end_turn()
	check(table.perspective.feedback.label.text.contains("PLAYER 1 TURN"),"Player 1 turn cue appears")
	await create_timer(1.5).timeout
	check(not table.perspective.feedback.label.visible,"Turn cue dismisses automatically")
	c.hand_window.restore_hand()
	await screenshot(base,"table")
	app.return_to_title()
	await create_timer(0.3).timeout
	check(app.table_scene == null and title.visible and is_equal_approx(title.modulate.a,1),"Return transition completes with tabletop disposed")
	check(title.buttons[1].has_focus(),"Last offline mode receives title focus")
	check(app.preferences.get_flag("last_offline"),"Last mode is stored without auto-start")
	check(is_equal_approx(float(app.table_preferences.value("hand_opacity",0)),0.5),"Returning preserves settings")
	check(app.entry.setup_ready == false,"Used setup does not contaminate future resumes")
	app.queue_free()
	await process_frame
	print("CARDLINK 7.6: %d checks, %d failures" % [checks,failures])
	quit(1 if failures else 0)
