extends "res://scripts/tests/milestone_6b_test.gd"
func run() -> void:
 var base: String=OS.get_cmdline_user_args()[0];root.size=Vector2i(1280,900);root.gui_embed_subwindows=true
 var a: Control=await create_client(base.path_join("a"),"Lab Alpha",Color.BLUE)
 var b: Control=await create_client(base.path_join("b"),"Lab Beta",Color.GREEN)
 for app: Control in [a,b]:
  for card: Control in app.tabletop.cards.duplicate():
   if card.state.card_definition_id.is_empty():app.tabletop.match_controller.remove_card(card)
 var m: Node=a.tabletop;var c: Node=m.match_controller;var lab: Node=m.lab
 check(lab!=null and m.temporary_images!=null,"Lab components initialized")
 c.library_actions.draw_n("local",6);var before: Array[String]=c.model.players.local.hand.duplicate();c.hand.refresh()
 var drop: Control=c.hand.row.get_child(4)
 drop._drop_data(Vector2(69,40),{"cardlink_instance":before[0]})
 check(c.model.players.local.hand[4]==before[0] and c.model.players.local.hand.size()==6,"Drag reorders six-card hand without dropping a card")
 check(c.hand.row.get_child(4).instance_id==before[0],"Hand UI follows saved private order")
 var hand_order: Array[String]=c.model.players.local.hand.duplicate();var snap: Dictionary=m.persistence.capture_match()
 check(preload("res://scripts/match_snapshot.gd").validate(snap).is_empty(),"Reordered hand snapshot validates")
 check(not m.persistence.restore_match(snap).has("error") and c.model.players.local.hand==hand_order,"Local Match Save restores hand order")
 c.library_actions.draw_n("local",1);check(c.model.players.local.hand.slice(0,6)==hand_order,"Draw appends after organized hand")
 c.move_card(c.card_by_id(before[0]),"graveyard");check(not before[0] in c.model.players.local.hand,"Discard works after reorder")
 for card: Control in m.cards.duplicate():c.move_card(card,"library",false)
 var original: Array[String]=c.pile.order.duplicate()
 check(lab.begin("local",5,false),"Look top five starts")
 check(lab.ids().size()==5 and c.pile.order.size()==original.size()-5,"Tray cards removed from drawable pile")
 check(lab.ids().all(func(id: String) -> bool:return c.card_by_id(id).state.visibility=="owner_private"),"Private look stays private")
 check(lab.cancel() and c.pile.order==original,"Cancel private review restores exact library order")
 lab.begin("local",5,true);var reviewed: Array[String]=lab.ids();var remainder: Array[String]=c.pile.order.duplicate()
 check(not lab.cancel(),"Already public review cannot undo revelation")
 lab.destination([reviewed[0]],"hand");lab.destination([reviewed[1]],"battlefield")
 var randomized: Array[String]=lab.destination(reviewed.slice(2),"random_bottom")
 check(c.pile.order.slice(0,remainder.size())==remainder,"Randomized Bottom leaves unselected library unchanged")
 check(c.pile.order.slice(remainder.size())==randomized and randomized.size()==3,"Only selected group placed on bottom")
 check(c.card_by_id(reviewed[0]).state.current_zone=="hand" and c.card_by_id(reviewed[1]).state.current_zone=="battlefield","Different subsets reach independent destinations")
 for id: String in reviewed:c.move_card(c.card_by_id(id),"library",false)
 lab.begin("local",3,true);reviewed=lab.ids();remainder=c.pile.order.duplicate();var group: Array[String]=lab.destination(reviewed,"random_top")
 check(c.pile.order.slice(0,3)==group and c.pile.order.slice(3)==remainder,"Randomized Top preserves remainder")
 lab.begin("local",2,true);reviewed=lab.ids();remainder=c.pile.order.duplicate();lab.destination(reviewed,"nth",3)
 check(c.pile.order.slice(2,4)==reviewed and c.pile.order.slice(0,2)==remainder.slice(0,2),"Nth group insertion is one-based and stable")
 for pair: Array in [["battlefield","random_bottom"],["hand","exile"],["exile","graveyard"]]:
  for card: Control in m.cards.duplicate():c.move_card(card,"library",false)
  lab.begin("local",1,true,true);lab.next_card();lab.next_card();lab.stop_here();var hit: String=lab.hit;reviewed=lab.ids();reviewed.erase(hit)
  lab.destination([hit],pair[0]);lab.destination(reviewed,pair[1]);check(c.card_by_id(hit).state.current_zone==pair[0] and lab.ids().is_empty(),"Reveal Until hit -> "+pair[0]+", others -> "+pair[1])
 for card: Control in m.cards.duplicate():c.move_card(card,"library",false)
 check(c.library_actions.move_top_n("local",1,"exile")==1,"Exile Top 1")
 check(c.library_actions.move_top_n("local",3,"exile")==3,"Exile Top N")
 var remaining_count: int=c.pile.order.size()
 check(c.library_actions.move_top_n("local",999,"exile")==remaining_count and c.pile.order.is_empty(),"Exile beyond remaining stops safely")
 var first: Control=m.cards[0];var second: Control=m.cards[1];c.move_card(first,"battlefield");c.move_card(second,"battlefield");first.state.owner_player_id="opponent";first.state.controller_player_id="local";second.state.controller_player_id="opponent";first.set_tapped(true);second.set_tapped(true)
 check(lab.untap_all()==1 and not first.tapped and second.tapped,"Untap All follows controller rather than owner")
 first.state.owner_player_id="local"
 lab.window.hide();m.controls.close_panels();first.set_tapped(true)
 var key:=InputEventKey.new();key.keycode=KEY_T;key.ctrl_pressed=true;key.alt_pressed=true;key.pressed=true
 check(m.shortcuts.bindings.action_for(key)=="untap_all","Ctrl+Alt+T maps to Untap All")
 m.shortcuts.handle_key(key);check(not first.tapped,"Ctrl+Alt+T executes controller-aware untap")
 var entry:=LineEdit.new();a.add_child(entry);entry.grab_focus();first.set_tapped(true);m.shortcuts.handle_key(key)
 check(first.tapped,"Untap shortcut pauses while typing");entry.release_focus();entry.queue_free()
 var im:=Image.create(160,80,false,Image.FORMAT_RGBA8);im.fill(Color.CORAL);var path: String=base.path_join("visual.png");im.save_png(path)
 m.temporary_images.assets.directory=base.path_join("images_a");b.tabletop.temporary_images.assets.directory=base.path_join("images_b")
 var image: Dictionary=m.temporary_images.spawn(path);check(image.has("id") and not image.has("error"),"Temporary image spawns outside Card Library")
 check(m.temporary_images.change(image.id,{"position":[300,400],"size":[320,160],"rotation":45,"opacity":0.5,"locked":true}),"Temporary image move resize rotate opacity lock")
 var copied: String=m.temporary_images.duplicate_image(image.id);check(not copied.is_empty() and copied!=image.id,"Temporary image duplicates with unique ID")
 m.temporary_images.remove(copied);check(not m.temporary_images.objects.has(copied),"Temporary image deletion")
 var bad_row: Dictionary=image.duplicate(true);bad_row.size=[50000,40];check(not m.temporary_images.put(bad_row),"Oversized object dimensions rejected")
 var bad_packet: Dictionary={"type":"playtest_image","protocol":1,"session_id":"a".repeat(32),"kind":"chunk","data":{"hash":image.hash,"total":9000000,"offset":0,"bytes":"AAAA"}}
 check(not preload("res://scripts/playtest_lab/image_protocol.gd").valid(bad_packet),"Oversized network image rejected")
 var trailing: PackedByteArray=FileAccess.get_file_as_bytes(path);trailing.append(1)
 check(not preload("res://scripts/network/card_sync_catalog.gd").png_complete(trailing),"Image transfer rejects trailing payload")
 check(m.temporary_images.spawn(base.path_join("bad.exe")).has("error"),"Executable file rejected")
 var f:=FileAccess.open(base.path_join("broken.png"),FileAccess.WRITE);f.store_string("not an image");f.close();check(m.temporary_images.spawn(base.path_join("broken.png")).has("error"),"Malformed image rejected")
 snap=m.persistence.capture_match();check(preload("res://scripts/match_snapshot.gd").validate(snap).is_empty(),"Temporary image local snapshot validates")
 check(not m.persistence.restore_match(snap).has("error") and m.temporary_images.objects.has(image.id),"Temporary image local save restores")
 var na: Node=a.get_node("Network").network;var nb: Node=b.get_node("Network").network;var ra: Node=a.get_node("Network").gameplay;var rb: Node=b.get_node("Network").gameplay
 var port: int=randi_range(35000,46000);na.host_game(port,"Host","127.0.0.1");nb.join_game("127.0.0.1",port,"Guest")
 check(await wait_for(func() -> bool:return na.session.state=="connected" and nb.session.state=="connected"),"Two playtest clients connect over LAN")
 check(await wait_for(func() -> bool:return b.tabletop.temporary_images.objects.has(image.id) and b.tabletop.temporary_images.assets.texture(image.hash)!=null),"Temporary image and verified bytes synchronize")
 b.tabletop.temporary_images.change(image.id,{"rotation":90,"position":[555,222]})
 check(await wait_for(func() -> bool:return m.temporary_images.objects[image.id].rotation==90 and int(m.temporary_images.objects[image.id].position[0])==555 and int(m.temporary_images.objects[image.id].position[1])==222),"Guest image transform mirrors to host")
 ra.start();rb.start();await wait_for(func() -> bool:return ra.card_sync.checked and rb.card_sync.checked);ra.card_sync.decide("sync");rb.card_sync.decide("sync")
 await wait_for(func() -> bool:return ra.card_sync.status.begins_with("CARD SYNC COMPLETE") and rb.card_sync.status.begins_with("CARD SYNC COMPLETE"),20)
 ra.card_sync.decide("start");rb.card_sync.decide("start");check(await wait_for(func() -> bool:return ra.enabled and rb.enabled),"Shared play starts after Card Sync")
 for card: Control in m.cards.duplicate():
  if card.state.owner_player_id=="local":c.move_card(card,"library",false)
 await settle();wire.clear();lab.begin("local",3,false);var private_ids: Array[String]=lab.ids();await settle()
 check(private_ids.all(func(id: String) -> bool:return not rb.state.cards.has(id) and not JSON.stringify(wire).contains(id)),"Private review IDs never enter online wire")
 ra.resync.apply(ra.state,ra.committed);check(lab.ids()==private_ids,"Resync preserves private review")
 check(lab.cancel(),"Private online review cancels safely")
 lab.begin("local",5,true);reviewed=lab.ids();await settle()
 check(reviewed.all(func(id: String) -> bool:return rb.state.cards.has(id)),"Five revealed tray cards mirror publicly")
 check(lab.ids().size()==5,"Host projection retains temporary tray membership")
 remainder=c.pile.order.duplicate();group=lab.destination(reviewed.slice(1),"random_bottom");lab.destination([reviewed[0]],"battlefield");await settle()
 check(c.pile.order.slice(0,remainder.size())==remainder,"Online randomized return leaves private remainder untouched")
 check(await wait_for(func() -> bool:return b.tabletop.match_controller.remote_library_knowledge.size()>=4),"Randomized result shared through revealed-only library knowledge")
 var same: bool=true
 for i: int in group.size():
  var row: Dictionary=b.tabletop.match_controller.remote_library_knowledge.get(str(remainder.size()+i),{})
  if row.get("id","")!=group[i]:same=false
 check(same,"Both clients agree on randomized selected-card positions")
 c.library_actions.draw_n("local",5);await settle();wire.clear();before=c.model.players.local.hand.duplicate();c.hand.refresh()
 if before.size()>=2:c.hand.row.get_child(1)._drop_data(Vector2(69,40),{"cardlink_instance":before[0]})
 await settle();check(not wire.any(func(frame: Dictionary) -> bool:return frame.type=="game"),"Private hand reordering sends no public gameplay action")
 var other_lab: Node=b.tabletop.lab;other_lab.begin("local",2,true);var guest_ids: Array[String]=other_lab.ids()
 check(await wait_for(func() -> bool:return guest_ids.all(func(id: String)->bool:return ra.state.cards.has(id))),"Guest review cards mirror to host")
 other_lab.destination(guest_ids,"exile")
 check(await wait_for(func()->bool:return guest_ids.all(func(id: String)->bool:return ra.state.cards.get(id,{}).get("zone","")=="exile")),"Guest bulk Exile mirrors to host")
 m.temporary_images.remove(image.id);check(await wait_for(func() -> bool:return not b.tabletop.temporary_images.objects.has(image.id)),"Temporary image delete mirrors")
 na.disconnect_session();await settle();a.queue_free();b.queue_free();await process_frame
 print("REVIEW LAB: %d checks, %d failures" % [checks,failures]);quit(0 if failures==0 else 1)
